name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install root deps
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate --schema=prisma/schema.prisma
      - name: Run backend tests
        run: |
          cd backend
          npm ci
          npm run test --silent
