name: CI
on:
  pull_request:
  push:
    branches: [ main, master, ai_main_* ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: TypeScript check
        run: npx tsc -p tsconfig.json --noEmit
      - name: Build Next
        env:
          # Provide a stub DB URL so prisma client compiles; not used at build-time
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?sslmode=disable
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install deps
        run: npm ci
      - name: ESLint (if configured)
        run: npm run lint --if-present
      - name: TypeScript check
        run: npx tsc -p tsconfig.json --noEmit
      - name: Build Nest
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?sslmode=disable
        run: npm run build
